### ISSUE TITLE
Warning Spamming in Log

### ISSUE THREAD

**Issue by walrusone** [Fuzss/visualworkbench-fabric#3] opened 2022-04-13 23:33 UTC
Getting the following warnings spamming in the log while moving around the server. Everything seems to be working correctly, just annoying that it is filling up the log.

[21:00:09] [Server thread/WARN]: Tried to load a block entity for block Block{minecraft:smithing_table} but failed at location class_2338{x=2862, y=-26, z=1338}
[21:00:16] [Server thread/WARN]: Tried to load a block entity for block Block{minecraft:smithing_table} but failed at location class_2338{x=2698, y=-1, z=950}
[21:00:19] [Server thread/WARN]: Tried to load a block entity for block Block{minecraft:fletching_table} but failed at location class_2338{x=2667, y=25, z=910}
[21:00:25] [Server thread/WARN]: Tried to load a block entity for block Block{minecraft:smithing_table} but failed at location class_2338{x=2783, y=13, z=1420}
[21:00:38] [Server thread/WARN]: Tried to load a block entity for block Block{minecraft:smithing_table} but failed at location class_2338{x=3070, y=-16, z=1546}

**Comment by Fuzss** [comment] 2022-04-30 13:11
I can't reproduce this, but I found where the message is printed from. So should be fixed in v.3.3.0. Please reopen if it's not.

**Closed as completed by Fuzss** 2022-04-30 13:11 UTC
